name: Release

on:
  push:
    branches:
      - master
      - beta
      - alpha

jobs:
  publish-package:
    name: Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build:library

      - name: Publish library
        run: npm run release:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
