name: Test
on:
  pull_request:
  push:
    branches:
      - master
      - beta
      - alpha

jobs:
  run-linter:
    name: Code Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint:ci

  run-type:
    name: Code Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'

      - name: Install dependencies
        run: npm ci

      - name: Run test:ci
        run: npm run type:ci

  run-test:
    name: Code Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'

      - name: Install dependencies
        run: npm ci

      - name: Run test:ci
        run: npm run test:ci

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage

  build-storybook:
    needs:
      - run-linter
      - run-type
      - run-test
    name: Build storybook
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'

      - name: Install dependencies
        run: npm ci

      - name: Check build script
        run: npm run build:storybook

  build-library:
    needs:
      - run-linter
      - run-type
      - run-test
    name: Build library
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'

      - name: Install dependencies
        run: npm ci

      - name: Check build script
        run: npm run build:library
